emancu/toml-rb

.hound.yml
.rubocop.yml
.travis.yml
Rakefile
init.rb
lib/toml.rb
lib/toml/dumper.rb
lib/toml/grammars/primitive.citrus
lib/toml/keyvalue.rb
lib/toml/multilined.rb
lib/toml/string.rb
test/dumper_test.rb
test/errors_test.rb
test/example-v0.3.0.toml
test/grammar_test.rb
test/toml_test.rb
toml-rb.gemspec

Multiline strings

---

lib/toml/grammars/primitive.citrus
test/example-v0.3.1.toml
test/grammar_test.rb
test/toml_examples.rb
test/toml_test.rb

Support datetime rfc 3339

---

lib/toml/grammars/document.citrus
lib/toml/grammars/primitive.citrus
lib/toml/keygroup.rb
test/grammar_test.rb
test/hard_example.toml
test/toml_examples.rb

Support quoted keys

---

lib/toml/grammars/array.citrus
test/grammar_test.rb

Accept comments between array’s elements.

---

lib/toml/dumper.rb
test/dumper_test.rb

Dump quoted keys

---

init.rb
lib/toml/array_tables.rb
lib/toml/dumper.rb
lib/toml/grammars/document.citrus
lib/toml/keygroup.rb
lib/toml/parser.rb
lib/toml/table_array.rb
test/dumper_test.rb
test/example-v0.3.1.toml
test/hard_example.toml
test/toml_examples.rb
test/toml_test.rb

Support array of tables

---

lib/toml/table_array.rb
test/hard_example.toml
test/toml_examples.rb

Table array parse error

---

lib/toml/table_array.rb
test/hard_example.toml
test/toml_examples.rb

Parent key for table array

---

.gems
lib/toml/inline_table.rb
lib/toml/keyvalue.rb
lib/toml/parser.rb
test/example.toml
test/grammar_test.rb
test/toml_examples.rb
test/toml_test.rb

Symbolize keys for inline tables

---

lib/toml/grammars/array.citrus
test/grammar_test.rb

fixed array parsing to allow indented comments

---

lib/toml/keyvalue.rb
test/errors_test.rb

Include duplicate key in ValueOverwriteError message

---

lib/toml/keygroup.rb
test/errors_test.rb

Check duplicate table definitions

---

lib/toml/parser.rb

Use array instead of Set

---

lib/toml/dumper.rb
test/dumper_test.rb

Print empty tables from dumper

---

lib/toml/grammars/primitive.citrus
test/examples/valid/multiline-string.json
test/examples/valid/multiline-string.toml

Multiline string parse error

---

lib/toml/dumper.rb
test/dumper_test.rb

Dumping array tables

---

lib/toml/parser.rb
lib/toml/table_array.rb
test/examples/valid/table-array-nest.json
test/examples/valid/table-array-nest.toml

Parsing array tables containing tables

---

init.rb
lib/toml/array.rb
lib/toml/grammars/array.citrus
lib/toml/keygroup.rb
test/examples/valid/arrays.json
test/examples/valid/arrays.toml

Multiline strings in arrays

---

.travis.yml
lib/toml-rb/table_array.rb
test/example.toml
test/toml_examples.rb
test/toml_test.rb

Fix symbolize keys for array tables

---

.travis.yml

I have a feeling this is broken in ruby 3, segfaulting in citrus.

Test against ruby 3.0.0

---

lib/toml-rb/string.rb
test/grammar_test.rb
test/toml_examples.rb
toml-rb.gemspec

Standard RB released a new version

---

.github/workflows/ruby.yml
test/grammar_test.rb

With the new Ruby version released 2 weeks ago, it is time to add it to CI

Add Ruby 3.1 and fix linter

---

.github/workflows/ruby.yml
toml-rb.gemspec

Add ruby 3.3 to testing matrix
